#!/bin/bash

echo "Sending attack..."
curl -X POST http://localhost:3000/attack \
-H "Content-Type: application/json" \
-d '{
  "username": "player1",
  "score": 2000
}'
echo ""

echo "Checking attack (first check)..."
curl -X GET "http://localhost:3000/checkAttack?username=player2"
echo ""

echo "Checking attack (second check)..."
curl -X GET "http://localhost:3000/checkAttack?username=player2"
echo ""
